export default {
  2024: [
    {
      title: "Schema.org : définition",
      url: "https://www.sfeir.dev/schema-org-definition/",
      publishedAt: "21 novembre 2024",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title: "L’accessibilité au DevFest Lille 2024",
      url: "https://www.sfeir.dev/front/laccessibilite-au-devfest-lille-2024/",
      publishedAt: "26 août 2024",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title: "Devfest Lille 2024 : vers un numérique responsable et performant",
      url: "https://www.urbilog.com/blogposts/devfest-lille-2024-vers-un-numerique-responsable-et-performant",
      publishedAt: "20 août 2024",
      publishedBy: "Urbilog",
      type: "press",
    },
    {
      title: "Summary of Devfest Lille 2024",
      url: "https://techblog.criteo.com/summary-of-devfest-lille-2024-9ad32eb4aa3a",
      publishedAt: "18 juillet 2024",
      publishedBy: "Criteo",
      type: "press",
    },
    {
      title: "Retour sur le jour 2 du Devfest Lille 2024 !",
      url: "https://www.sfeir.dev/tendances/retour-sur-le-jour-2-du-devfest-lille-2024-2/",
      publishedAt: "01 juillet 2024",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title: "Retour sur le DevFest 2024 : une édition inoubliable !",
      url: "https://www.sfeir.dev/tendances/retour-sur-le-devfest-2024-une-edition-inoubliable/",
      publishedAt: "18 juin 2024",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title: "De retour du DevFest Lille 2024",
      url: "https://les-tilleuls.coop/blog/de-retour-du-devfest-lille-2024",
      publishedAt: "17 juin 2024",
      publishedBy: "Les Tilleuls",
      type: "press",
    },
    {
      title: "Un petit compte-rendu subjectif du DevFest Lille 2024",
      url: "https://medium.com/norsys-octogone/un-petit-compte-rendu-subjectif-du-devfest-lille-2024-f80e042bdf4d",
      publishedAt: "13 juin 2024",
      publishedBy: "Norsys",
      type: "press",
    },
    {
      title: "Holberton était présent à la 7ème édition du DevFest Lille !",
      url: "https://www.holbertonschool.fr/post/holberton-etait-present-a-la-7eme-edition-du-devfest-lille",
      publishedAt: "13 juin 2024",
      publishedBy: "Holberton School",
      type: "press",
    },
    {
      title: "DevFest Lille 2024 : highlights et conférences marquantes",
      url: "https://fr.ippon.tech/news/devfest-lille",
      publishedAt: "06 juin 2024",
      publishedBy: "Ippon Technologies",
      type: "press",
    },
  ],
  2023: [
    {
      title:
        "Parlons Tech – L’EMPREINTE NUMÉRIQUE avec Baptiste / DevFest Lille 2023",
      url: "https://welovedevs.com/fr/articles/youtube-parlons-tech-empreinte-numerique-avec-baptiste-devfest-lille-2023/",
      publishedAt: "11 septembre 2023",
      publishedBy: "WeLoveDevs",
      type: "video",
    },
    {
      title:
        "Parlons Tech – LE DESIGN D’ATTENTION avec Alizée / DevFest Lille 2023",
      url: "https://welovedevs.com/fr/articles/youtube-parlons-tech-le-design-dattention-avec-alizee-devfest-lille-2023/",
      publishedAt: "22 août 2023",
      publishedBy: "WeLoveDevs",
      type: "video",
    },
    {
      title: "Clean Architecture et Serverless : retour sur le Devfest 2023",
      url: "https://www.hubvisory.com/fr/blog/clean-architecture-et-serverless-devfest-2023",
      publishedAt: "15 août 2023",
      publishedBy: "Hubvisory",
      type: "press",
    },
    {
      title: "DevFest Lille : Les retours de conf' de nos Sfeiriens - Partie 2",
      url: "https://www.sfeir.dev/tendances/devfest-lille-les-retours-de-conf-de-nos-sfeiriens-partie-2/",
      publishedAt: "08 juin 2023",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title:
        "Le DevFest de Lille 2023 s’ouvre avec une sensibilisation au design d’attention",
      url: "https://digital4better.com/actualites/le-devfest-de-lille-2023-s%E2%80%99ouvre-avec-une-sensibilisation-au-design-d%E2%80%99attention/",
      publishedAt: "06 juin 2023",
      publishedBy: "Alizée Colin",
      type: "press",
    },
    {
      title:
        "L'accessibilité et l'inclusivité au travail : des piliers fondamentaux au cœur du DevFest Lille",
      url: "https://www.sfeir.dev/tendances/laccessibilite-et-linclusivite-au-travail-des-piliers-fondamentaux-au-coeur-du-devfest-lille/",
      publishedAt: "06 juin 2023",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title: "DevFest Lille 2023 : Les retours de conf' de nos Sfeiriens",
      url: "https://www.sfeir.dev/tendances/devfest-lille-2023-les-retours-de-conf-de-nos-sfeiriens/",
      publishedAt: "1 juin 2023",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title: "Cockpit io au Devfest Lille 2023",
      url: "https://blog.cockpitio.com/events/devfest-lille-2023/",
      publishedAt: "30 mai 2023",
      publishedBy: "Cockpit IO",
      type: "press",
    },
    {
      title: "DevFest Lille 2023 : une conférence dans l’ère du temps !",
      url: "https://www.sfeir.dev/tendances/un-devops-au-devfest-lille-2023/",
      publishedAt: "26 mai 2023",
      publishedBy: "Sfeir",
      type: "press",
    },
    {
      title:
        "Le DevFest Lille 2023 : l’événement tech se prépare avec Le Messageur pour une accessibilité pour tous.",
      url: "https://www.lemessageur.com/le-devfest-lille-2023-levenement-tech-se-prepare-avec-le-messageur-pour-une-accessibilite-pour-tous/",
      publishedAt: "15 mai 2023",
      publishedBy: "Le Messageur",
      type: "press",
    },
    {
      title:
        "Le DEVFEST Lille : un événement engagé pour la technologie et l’environnement !",
      url: "https://consignerie.com/le-devfest-lille-un-evenement-engage-pour-la-technologie-et-lenvironnement/",
      publishedAt: "12 mai 2023",
      publishedBy: "La Consignerie",
      type: "press",
    },
    {
      title: "Réduire l’impact environnemental du Devfest Lille",
      url: "https://welovedevs.com/fr/articles/reduire-limpact-environnemental-du-devfest-lille/",
      publishedAt: "19 avril 2023",
      publishedBy: "WeLoveDevs",
      type: "press",
    },
  ],
  2022: [
    {
      title: "Retour sur DevFest Lille 2022",
      url: "https://www.dnd.fr/retour-sur-devfest-lille-2022/",
      publishedAt: "05 juillet 2022",
      publishedBy: "Dn'D",
      type: "press",
    },

    {
      title: "DevFest Lille 2022: our insights",
      url: "https://medium.com/adeo-tech/devfest-lille-2022-8a9104ef020a",
      publishedAt: "20 juin 2022",
      publishedBy: "Adeo",
      type: "press",
    },
    {
      title: "[REX] DevFest Lille 2022 🍻",
      url: "https://maximepawlak.medium.com/rex-devfest-lille-2022-9814f45eea52",
      publishedAt: "13 juin 2022",
      publishedBy: "Maxime Pawlak",
      type: "press",
    },
  ],
};
